const fs=require('fs'),assert=require('assert/strict'),path=require('path');
const {JSDOM}=require(process.env.BALANCE_JSDOM_PATH||'jsdom');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(root+'/index.html','utf8'),settings=JSON.parse(fs.readFileSync(root+'/balance-config.json','utf8'));
(async()=>{
 const vm=require('vm');const dom=new JSDOM(html,{url:'https://balance.test/index.html',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 for(const [k,v] of Object.entries({TextDecoder,TextEncoder,DecompressionStream,Response,Blob,AbortController,fetch:async()=>new Response(JSON.stringify(settings))}))w[k]=v;
 w.URL.createObjectURL=()=> 'blob:download-test';w.URL.revokeObjectURL=()=>{};
 const ctx=dom.getInternalVMContext(),run=s=>vm.runInContext(s,ctx);run(w.document.querySelector('script:not([type])').textContent);
 await run('bootReady');const d=w.document;
 assert.equal(d.getElementById('exportCsv'),null);assert.equal(d.querySelectorAll('#exportXlsx').length,1);assert.equal(d.getElementById('exportXlsx').closest('.header-search')!==null,true);
 assert.equal(d.getElementById('printReport').closest('.header-search')!==null,true);
 assert.ok(d.getElementById('kpis').classList.contains('hidden'));assert.equal(d.querySelectorAll('[data-owner]').length>0,true);
 d.querySelector('[data-owner="Подрядчик 1"]').click();assert.ok(!d.getElementById('kpis').classList.contains('hidden'));
 const search=d.getElementById('metricSearch');search.value='Банковская';search.dispatchEvent(new w.Event('input'));
 assert.ok(d.body.classList.contains('metric-searching'));assert.equal(w.getComputedStyle(d.querySelector('.balance-table')).height,'auto');
 assert.equal(w.getComputedStyle(d.getElementById('balanceColumn')).height,'auto');
 search.value='';search.dispatchEvent(new w.Event('input'));assert.ok(!d.body.classList.contains('metric-searching'));
 d.getElementById('allContractors').click();assert.ok(d.getElementById('kpis').classList.contains('hidden'));
 d.getElementById('ownerAiMode').click();assert.equal(d.getElementById('ownerAiMode').getAttribute('aria-pressed'),'false');
 d.getElementById('ownerSearch').value='Подрядчик 10';d.getElementById('ownerSearch').dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('[data-owner]').length,1);
 d.getElementById('ownerAiMode').click();assert.equal(d.getElementById('ownerAiMode').textContent,'ИИ');
 run('config.aiSearch={endpoint:"https://ai.example.test/v1/chat/completions",model:"test-model",apiKey:"test-only-key",mode:"ai"}');let calls=0;w.fetch=async()=>{calls++;return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({groups:[[{field:'name',op:'eq',value:'Подрядчик 1'}]]})}}]}));};
 await run('runAiSearch()');assert.equal(calls,1);assert.equal(d.querySelectorAll('[data-owner]').length,1);assert.equal(d.querySelector('[data-owner]').dataset.owner,'Подрядчик 1');

 assert.equal(d.querySelector('.sibur-wordmark').textContent,'СИБУР');assert.equal(d.querySelector('.brand').firstElementChild.className,'sibur-wordmark');
 assert.equal(w.getComputedStyle(d.getElementById('exportXlsx')).height,w.getComputedStyle(d.getElementById('ownerSearch')).height);
 assert.equal(w.getComputedStyle(d.getElementById('printReport')).height,w.getComputedStyle(d.getElementById('metricSearch')).height);
 assert.equal(d.getElementById('currentDate').textContent,run('currentDateParts().text'));assert.equal(d.getElementById('currentDate').getAttribute('datetime'),run('currentDateParts().iso'));
 d.getElementById('metricAiMode').click();assert.equal(d.getElementById('metricAiMode').getAttribute('aria-pressed'),'true');
 d.getElementById('metricSearch').value='гарантийные удержания';d.getElementById('metricSearch').dispatchEvent(new w.Event('input'));
 w.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({rows:[32]})}}]}));await run('runMetricAiSearch()');
 assert.equal(d.querySelectorAll('[data-source-row="33"]').length,1);assert.equal(d.querySelectorAll('[data-source-row="34"]').length,1);
 d.getElementById('metricSearch').value='';d.getElementById('metricSearch').dispatchEvent(new w.Event('input'));assert.ok(d.getElementById('metricAiStatus').classList.contains('hidden'));
 d.getElementById('editToggle').click();d.getElementById('adminSide').click();assert.equal(d.querySelector('[data-ai="apiKey"]').type,'password');assert.equal(d.querySelector('[data-ai="model"]').value,'test-model');
 // Native selector changes are included when settings are applied, even without blur.
 const model=d.querySelector('[data-ai="model"]');model.value='test-model';assert.equal(run('getDraft().aiSearch.model'),'test-model');
 const reopenedHtml=run('configuredHtml(getDraft())');assert.ok(reopenedHtml.includes('const BOOT_CONFIG = {'));
 assert.equal(new JSDOM(reopenedHtml).window.document.querySelectorAll('#exportXlsx').length,1);
 dom.window.close();console.log(JSON.stringify({status:'PASS',checks:['native DOM startup','single exports in header','KPI scope','natural table and panel height while filtering','AI icon toggle','text filter','AI local result selection','masked config editor','exported autonomous HTML']}));
})().catch(e=>{console.error(e.message);process.exit(1)});
