// Проверка настоящей книги: ZIP/XML, все значения, фильтры, итоги, экспорт и настройки.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const xmljs=require('xml-js'),root=path.resolve(__dirname,'..');
class XmlNode{constructor(n){this.n=n;}getAttribute(k){return this.n.attributes?.[k]??null;}getAttributeNS(ns,k){return this.getAttribute('r:'+k);}get textContent(){function t(n){return (n.text||n.cdata||'')+(n.elements||[]).map(t).join('');}return t(this.n);}getElementsByTagNameNS(ns,name){const out=[];function walk(n){for(const c of n.elements||[]){if(c.type==='element'&&c.name.split(':').at(-1)===name)out.push(new XmlNode(c));walk(c);}}walk(this.n);return out;}getElementsByTagName(name){return this.getElementsByTagNameNS('*',name);}}
class DOMParser{parseFromString(s){return new XmlNode(xmljs.xml2js(s,{compact:false}));}}
const ids=new Map(),downloads=[];function element(id){if(ids.has(id))return ids.get(id);const classes=new Set(id==='modalBack'||id==='dashboard'?['hidden']:[]),e={id,value:'',textContent:'',innerHTML:'',dataset:{},checked:false,disabled:false,onclick:null,classList:{contains:x=>classes.has(x),add:x=>classes.add(x),remove:x=>classes.delete(x),toggle:(x,on)=>{if(on)classes.add(x);else classes.delete(x);}},querySelector:()=>element(id+'-sub'),contains:()=>false,focus:()=>{},setAttribute:()=>{},scrollIntoView:()=>{},dispatchEvent:()=>{},append:()=>{},remove:()=>{},click(){if(this.download)downloads.push(this.download);}};ids.set(id,e);return e;}
const document={getElementById:element,querySelectorAll:()=>[],addEventListener:()=>{},createElement:()=>element('anchor'),body:Object.assign(element('body'),{append:()=>{}}),activeElement:null};
const context={console,DOMParser,document,location:{href:'https://example.test/index.html'},Blob,Response,DecompressionStream,TextEncoder,TextDecoder,Uint8Array,DataView,URL,AbortController,setTimeout:(fn,ms)=>{const t=setTimeout(fn,ms);t.unref();return t;},clearTimeout,Event,atob,btoa,fetch:()=>{throw Error('Unexpected network');},window:{print:()=>{}},alert:()=>{}};
vm.createContext(context);const scripts=['core','xlsx-reader','zip-writer','app','admin'].map(n=>fs.readFileSync(root+'/src/'+n+'.js','utf8')).join('\n');vm.runInContext('const BOOT_CONFIG=null;\n'+scripts,context);
function run(s){return vm.runInContext(s,context);}function approx(a,b){assert.ok(Math.abs(a-b)<Math.max(1e-8,Math.abs(b)*1e-12),`${a} ≠ ${b}`);}
(async()=>{
 const input=process.argv[2]||root+'/data/source.xlsx',raw=fs.readFileSync(input);context.input=raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength);element('scale').value='1000000';element('decimals').value='0';element('currencyMode').value='rub';element('vatMode').value='gross';
 element('showContractorTotal').checked=true;
 await run("loadBook(input,'Исходная книга.xlsx','file')");assert.equal(run('book.sheets.length'),4);assert.equal(run('allOwners().length'),25);assert.equal(run('currentReport().columns.length'),32);assert.equal(run('rConfig().vat'),'gross');assert.equal(run('currentReport().date'),'15.09.2026');
 // Сверка значений с независимым чтением исходного Excel (openpyxl data_only).
 const independent=JSON.parse(fs.readFileSync(root+'/tests/source-expected.json','utf8'));let count=0;
 for(const [name,cells] of Object.entries(independent))for(const [ref,c] of Object.entries(cells))if(c.v!==null&&typeof c.v==='number'){const value=run(`(()=>{const s=book.sheets.find(s=>s.name===${JSON.stringify(name)}),p=address(${JSON.stringify(ref)});return s.rows[p.row]?.[p.col]})()`);approx(value,c.v);count++;}
 const expectedCounts=[32,8,8,31];for(let i=0;i<4;i++)assert.equal(run(`extractReport(book,config.reports[${i}]).columns.length`),expectedCounts[i]);
 run("$('detailLevel').value='3'");
 // Общий баланс сохраняет все исходные строки и собирает каждую сумму по договорам подрядчика.
 let aggregateChecks=0;for(let i=0;i<4;i++){
  run(`activeReport=config.reports[${i}].id;owner=null;tab='summary';$('currencyMode').value=config.reports[${i}].currencyMode;resetSelection();render()`);
  const report=run('currentReport()'),groups=run('summaryGroups(currentReport(),selectedColumns(currentReport()))');
  for(const group of groups)for(const row of report.rows.filter(row=>!row.section&&row.type==='money')){
   const values=group.columns.map(c=>independent[report.report.sheet][c.letter+row.row]?.v).filter(v=>typeof v==='number');if(!values.length)continue;
   context.groupColumns=group.columns;context.groupRow=row;context.aggregateCurrency=group.currency;
   approx(run('totals(currentReport(),groupColumns,groupRow,targetCurrency())[aggregateCurrency].value'),values.reduce((a,b)=>a+b,0)*report.report.sourceScale);aggregateChecks++;
  }
  assert.ok(element('reportArea').innerHTML.includes(report.rows[0].label));assert.equal((element('reportArea').innerHTML.match(/data-source-row=/g)||[]).length,run('viewRows(currentReport()).length'));for(const row of report.rows.filter(row=>row.visible!==false))assert.ok(element('reportArea').innerHTML.includes('data-source-row=\"'+row.row+'\"'),`Missing rendered source row ${row.row}`);assert.ok(element('reportArea').innerHTML.includes(report.rows.at(-1).label));assert.ok(element('sourceReport').innerHTML.includes('Валюта · без НДС'));
 }
 run("activeReport='rub-gross';owner=null;tab='summary';$('currencyMode').value='rub';resetSelection();render()");
 const fullTotal=run('totalText(currentReport(),selectedColumns(currentReport()),currentReport().rows.find(row=>row.row===12),false)');run("$('detailLevel').value='2';render()");assert.ok(!element('reportArea').innerHTML.includes('data-source-row=\"14\"'));assert.ok(element('reportArea').innerHTML.includes('data-source-row=\"13\"'));assert.equal(run('totalText(currentReport(),selectedColumns(currentReport()),currentReport().rows.find(row=>row.row===12),false)'),fullTotal);run("$('detailLevel').value='1';render()");assert.equal(run('viewRows(currentReport()).filter(row=>row.level===1).map(row=>row.headingLabel).join(",")'),'Выполнено,Профинансировано,Задолженность,Обеспечение,Баланс');assert.ok(!element('reportArea').innerHTML.includes('data-source-row=\"13\"'));run("$('detailLevel').value='3';render()");
 assert.equal(run('currentReport().rows.find(row=>row.row===14).indent'),3);assert.equal(run('currentReport().rows[0].strong'),true);assert.ok(element('reportArea').innerHTML.includes('padding-left:24px'));assert.ok(element('reportArea').innerHTML.includes('data-open-owner=\"Подрядчик 25\"'));assert.ok(element('reportArea').innerHTML.includes('Нет в исходном листе'));
 assert.equal(run('summaryGroups(currentReport(),selectedColumns(currentReport())).length'),25);
 assert.equal(run('summaryGroups(currentReport(),selectedColumns(currentReport())).find(g=>g.name==="Подрядчик 25").available.length'),0);
 const summaryRows=run('exportRows()');assert.equal(summaryRows[9][1],'Итого');assert.equal(summaryRows[9][2],'Подрядчик 1');assert.ok(!summaryRows[9].some(s=>String(s).startsWith('Дог.')));
 approx(summaryRows[13][2],Math.round(independent['БАЛАНС РУКОВОДСТВУ руб. с НДС'].D5.v+independent['БАЛАНС РУКОВОДСТВУ руб. с НДС'].E5.v));
 const summaryBlob=run('xlsxFile(exportRows())');context.summaryBuffer=await summaryBlob.arrayBuffer();const summaryBook=await run('readWorkbook(summaryBuffer,"summary.xlsx")');
 assert.equal(summaryBook.sheets[0].rows[9][2],'Подрядчик 1');assert.equal(summaryBook.sheets[0].cellStyles.A14.bold,true);const indentedIndex=run('viewRows(currentReport()).findIndex(row=>row.row===14)')+14;assert.equal(summaryBook.sheets[0].cellStyles['A'+indentedIndex].indent,3);
 run("activeReport='rub-net';owner='Подрядчик 1';tab='summary';resetSelection();render()");assert.equal(run('currentReport().rows.find(row=>row.row===28).spacer'),true);
 const percentRows=run('exportRows()'),percent=percentRows.find(row=>row[0]==='Доля НЗП от выполненных работ');
 approx(percent[1],(independent['Преза НЗП без НДС'].E8.v+independent['Преза НЗП без НДС'].F8.v)/(independent['Преза НЗП без НДС'].E6.v+independent['Преза НЗП без НДС'].F6.v));
 run('setEditing(true)');assert.equal(document.body.classList.contains('editing'),true);run('sourceDialog()');assert.equal(element('modalTitle').textContent,'Источники баланса');run('setEditing(false)');assert.equal(document.body.classList.contains('editing'),false);assert.equal(element('modalBack').classList.contains('hidden'),true);run('admin();sourceDialog()');assert.equal(element('modalBack').classList.contains('hidden'),true);
 run("activeReport='rub-gross';chooseOwner('Подрядчик 25')");assert.equal(run('activeReport'),'rub-net');assert.equal(run('tab'),'detail');assert.equal(run('reportHasOwner(config.reports.find(r=>r.id==="fx-gross"))'),false);assert.ok(element('sourceReport').innerHTML.includes('value=\"fx-gross\" disabled'));run("openReport('fx-gross')");assert.equal(run('activeReport'),'rub-net');
 run("activeReport='rub-net';chooseOwner('Подрядчик 17')");assert.equal(run('activeReport'),'fx-net');assert.equal(run('rConfig().vat'),'net');
 element('embedded-source').textContent=raw.toString('base64');await run('boot()');assert.equal(run('sourceInfo.kind'),'embedded');assert.equal(run('allOwners().length'),25);assert.equal(element('welcome').classList.contains('hidden'),true);assert.equal(run('activeReport'),'rub-gross');assert.equal(run('rConfig().vat'),'gross');assert.equal(element('detailLevel').value,'2');assert.ok(element('pageTitle').textContent.includes('с НДС'));run("openReport('rub-net')");assert.equal(run('selectedValue(currentReport(),currentReport().columns[0],currentReport().rows.find(row=>row.row===27),targetCurrency())'),null);assert.ok(run('viewRows(currentReport()).every(row=>row.level<=2)'));assert.ok(!element('reportArea').innerHTML.includes('data-source-row=\"30\"'));run("$('detailLevel').value='3';render()");run("openReport('rub-gross')");assert.equal(run('activeReport'),'rub-gross');assert.ok(element('pageTitle').textContent.includes('с НДС'));
 run("chooseOwner('Подрядчик 1');tab='detail';render()");assert.equal(run('selectedColumns(currentReport()).length'),2);assert.ok(element('pageTitle').textContent.includes('Подрядчик 1'));assert.equal(element('sourceReport').value,'rub-gross');assert.equal(element('connectionStatus').className,'status-chip ok');assert.equal((element('reportArea').innerHTML.match(/data-source-row=/g)||[]).length,run('viewRows(currentReport()).length'));assert.ok(element('reportArea').innerHTML.includes('padding-left:24px'));
 const contract=run('currentReport().columns.find(c=>c.letter==="D")');context.contract=contract;approx(run('selectedValue(currentReport(),contract,currentReport().rows[0],"rub")'),independent['БАЛАНС РУКОВОДСТВУ руб. с НДС'].D5.v*1e6);
 assert.ok(!run('currentReport().columns.some(c=>c.letter==="C")'),'Aggregate C must be excluded');
 // Реальный обработчик галочек пересчитывает KPI и итог; скрытие итога не меняет выбранные договоры.
 for(const reportId of ['rub-gross','rub-net','fx-gross','fx-net']){
  run(`activeReport=${JSON.stringify(reportId)};chooseOwner('Подрядчик 1')`);
  const first=run('selectedColumns(currentReport())[0]');context.firstContract=first;
  run("$('contractChips').onchange({target:{dataset:{contract:firstContract.key},checked:false}})");
  assert.equal(run('selectedColumns(currentReport()).length'),1);assert.ok(!element('reportArea').innerHTML.includes(`<th>${first.contract}<small>`));
  const chosen=run('selectedColumns(currentReport())[0]'),r=run('currentReport()');
  approx(run('totals(currentReport(),selectedColumns(currentReport()),currentReport().rows[0],targetCurrency())[groupCurrency(currentReport(),selectedColumns(currentReport())[0],targetCurrency())].value'),independent[r.report.sheet][chosen.letter+r.rows[0].row].v*r.report.sourceScale);
  assert.ok(element('kpis').innerHTML.includes(run('totalText(currentReport(),selectedColumns(currentReport()),currentReport().rows[0],false)')));assert.equal(element('contractSummary').textContent,'Договоры · выбрано 1 из 2');
  element('showContractorTotal').checked=false;run("$('showContractorTotal').onchange()");assert.ok(!element('reportArea').innerHTML.includes('Итого по подрядчику'));assert.equal((element('reportArea').innerHTML.match(/<th(?:\s|>)/g)||[]).length,2);assert.equal(run('exportRows()[9].length'),2);
  run("$('selectNone').onclick()");assert.equal(run('selectedColumns(currentReport()).length'),0);assert.ok(element('kpis').innerHTML.includes('Нет данных'));assert.equal(element('exportXlsx').disabled,true);
  element('showContractorTotal').checked=true;run("$('showContractorTotal').onchange();$('selectAll').onclick()");assert.equal(run('selectedColumns(currentReport()).length'),2);assert.ok(element('reportArea').innerHTML.includes('Итого по подрядчику'));
 }
 run("activeReport='rub-gross';chooseOwner('Подрядчик 1');selected=new Set([contract.key]);render()");assert.equal(run('exportRows()[9].length'),2);const rows=run('exportRows()');assert.equal(rows[10][1],'Подрядчик 1');assert.equal(rows[9][1],'Дог.9756');assert.ok(!rows[9].includes('Дог.10675'));
 context.rows=rows;const blob=run('xlsxFile(rows)');const buffer=await blob.arrayBuffer();context.exported=buffer;const reread=await run('readWorkbook(exported,"export.xlsx")');assert.equal(reread.sheets.length,1);assert.equal(reread.sheets[0].rows[9][1],'Дог.9756');assert.equal(reread.sheets[0].rows[13][1],Math.round(independent['БАЛАНС РУКОВОДСТВУ руб. с НДС'].D5.v));fs.writeFileSync(root+'/../checked-export.xlsx',Buffer.from(buffer));
 run("activeReport='fx-gross';$('currencyMode').value='contract';owner='Подрядчик 1';resetSelection();render()");assert.equal(run('selectedColumns(currentReport()).length'),2);const currencyValue=run('selectedValue(currentReport(),selectedColumns(currentReport())[0],currentReport().rows[0],"contract")');approx(currencyValue,independent['Баланс ФЭК (валюта) с НДС'].E6.v*1e6);
 run("config.reports[1].columns.F={currency:'EUR'}");assert.deepEqual(Object.keys(run('totals(currentReport(),selectedColumns(currentReport()),currentReport().rows[0],"contract")')).sort(),['EUR','USD']);
 run("tab='summary'");assert.deepEqual(Array.from(run('exportRows()[11].slice(1,3)')).sort(),['EUR','USD']);run("tab='detail'");
 const fxRub=run('selectedValue(currentReport(),selectedColumns(currentReport())[0],currentReport().rows[0],"rub")');approx(fxRub,currencyValue*89.79);
 run("openReport('fx-net')");assert.equal(run('activeReport'),'fx-net');approx(run('selectedValue(currentReport(),selectedColumns(currentReport())[0],currentReport().rows[0],"contract")'),independent['Баланс ФЭК (валюта) без НДС'].E5.v*1e6);
 run("owner='Подрядчик 24';resetSelection();render()");assert.equal(run('selectedColumns(currentReport()).length'),0);assert.equal(element('exportXlsx').disabled,true);assert.ok(element('notice').textContent.includes('нет данных'));
 run("activeReport='rub-net';owner='Подрядчик 1';$('currencyMode').value='rub';resetSelection();render()");assert.equal(run('totalText(currentReport(),selectedColumns(currentReport()),currentReport().rows.find(r=>r.row===9),false)'),'—');
 assert.equal(run('displayedNumber(0,{type:"money"},1e6,0)'),'—');assert.equal(run('displayedNumber(null,{type:"money"},1e6,0)'),'Нет данных');assert.equal(run('displayedNumber(0.125,{type:"percent"},1e6,0)'),'12,5 %');assert.equal(run('displayedNumber(-50000000,{type:"money"},1e6,0)'),'-50');
 // Независимое раскрытие разделов, сохранение расчётов и исключение скрытых строк из выгрузки.
 run("activeReport='rub-gross';chooseOwner('Подрядчик 1');$('detailLevel').value='2';expandedRows.clear();render()");
 const fundingTotal=run('totalText(currentReport(),selectedColumns(currentReport()),currentReport().rows.find(r=>r.row===12),false)');
 run('toggleRow(12)');assert.ok(!element('reportArea').innerHTML.includes('data-source-row="13"'));assert.ok(element('reportArea').innerHTML.includes('data-source-row="8"'));
 run('toggleRow(12);toggleRow(13)');assert.ok(element('reportArea').innerHTML.includes('data-source-row="14"'));assert.equal(run('totalText(currentReport(),selectedColumns(currentReport()),currentReport().rows.find(r=>r.row===12),false)'),fundingTotal);
 run("$('detailLevel').onchange()");assert.ok(!element('reportArea').innerHTML.includes('data-source-row="14"'));run("$('detailLevel').value='3';$('detailLevel').onchange()");
 for(const n of [9,11]){assert.ok(run(`currentReport().rows.some(r=>r.row===${n})`));assert.ok(!element('reportArea').innerHTML.includes(`data-source-row="${n}"`));assert.ok(!run('exportRows()').some(row=>['Курсовая разница на приемку','Выполнено всего из отчета НЗП'].includes(row[0])));}
 // Видимость сохраняется в конфиге и исключает подрядчика из меню, итогов, KPI и экспортов.
 run('setEditing(true);admin()');const ownerIndex=run('adminDraft.contractors.findIndex(c=>c.name==="Подрядчик 1")');context.ownerIndex=ownerIndex;
 run('adminChange({target:{dataset:{ownerIndex:String(ownerIndex)},checked:false}});adminChange({target:{dataset:{global:"showKpis"},checked:false}});applyAdmin()');
 assert.equal(run('owner'),null);assert.ok(!element('ownerMenu').innerHTML.includes('data-owner="Подрядчик 1"'));assert.ok(run('selectedColumns(currentReport()).every(c=>c.contractor!=="Подрядчик 1")'));assert.ok(!run('exportRows()[9]').includes('Подрядчик 1'));assert.equal(element('kpis').innerHTML,'');
 const hiddenConfig=run('validateConfig(JSON.parse(JSON.stringify(config)))');assert.equal(hiddenConfig.showKpis,false);assert.equal(hiddenConfig.contractors.find(c=>c.name==='Подрядчик 1').visible,false);
 // Новый подрядчик скрыт до включения; администратор получает уведомление.
 context.savedConfig=run('clone(config)');context.oldOwner=run('book.sheets[0].rows[0][3]');
 run("book.sheets[0].rows[0][3]='Новый подрядчик';resetSelection();render()");assert.equal(run('newOwners().length'),1);assert.ok(!element('newOwnersNotice').classList.contains('hidden'));assert.ok(!element('ownerMenu').innerHTML.includes('data-owner="Новый подрядчик"'));assert.ok(run('selectedColumns(currentReport()).every(c=>c.contractor!=="Новый подрядчик")'));
 run('admin()');const newIndex=run('adminDraft.contractors.findIndex(c=>c.name==="Новый подрядчик")');context.newIndex=newIndex;assert.equal(run('adminDraft.contractors[newIndex].visible'),false);
 run('adminChange({target:{dataset:{ownerIndex:String(newIndex)},checked:true}});applyAdmin()');assert.ok(element('ownerMenu').innerHTML.includes('data-owner="Новый подрядчик"'));assert.equal(run('newOwners().length'),0);assert.ok(run('selectedColumns(currentReport()).some(c=>c.contractor==="Новый подрядчик")'));
 run("book.sheets[0].rows[0][3]=oldOwner;config=savedConfig;config.contractors.find(c=>c.name==='Подрядчик 1').visible=true;config.showKpis=true;resetSelection();render();setEditing(false)");
 const dateJson=run('JSON.stringify(DEFAULT_CONFIG)');fs.writeFileSync(root+'/config/balance-config.json',dateJson+'\n');
 // Ошибка формулы сохраняется; она не превращается в ноль.
 run("currentReport().sheet.rows[currentReport().rows[0].row-1][selectedColumns(currentReport())[0].index]='#NO_CACHED_FORMULA'");assert.equal(run('selectedValue(currentReport(),selectedColumns(currentReport())[0],currentReport().rows[0],"rub")'),'#NO_CACHED_FORMULA');
 // Применение изменённых настроек автоматически скачивает конфиг.
 run("setEditing(true);admin();adminDraft.title='Новый баланс';applyAdmin()");assert.ok(downloads.includes('balance-config.json'));assert.equal(run('config.title'),'Новый баланс');
 assert.throws(()=>run("validateConfig({...config,reports:config.reports.map(r=>({...r,sourceScale:0}))})"));
 assert.throws(()=>run("safeURL('javascript:alert(1)')"));
 assert.ok(!/(?:localStorage|sessionStorage|indexedDB)\s*[.(]|document\.cookie\s*=/.test(scripts));
 console.log(JSON.stringify({status:'PASS',sourceCellsCompared:count,aggregateChecks,reports:4,contractsPerReport:expectedCounts,contractorsUnion:25,checks:['automatic source startup','full contractor balances','all aggregate rows reconciled','source bold and indentation','summary XLSX roundtrip','weighted percentages','missing report availability','contract filters','no double counting','VAT source switch','currency isolation','FX conversion','missing data','rounding','contract XLSX export roundtrip','automatic config download','config validation','no browser persistence','single report selector','editing visibility and source modal','connection status states','gross VAT default','VAT-preserving contractor fallback','independent group expansion','hidden rows retained for calculations','KPI visibility config','contractor visibility in aggregates and exports','new contractor opt-in','unified balance heading','three reporting levels','default second level','totals invariant across levels']}));
})().catch(e=>{console.error(e);process.exitCode=1;});
