function admin(){if(!editing)return;adminDraft=clone(config);const known=new Set((adminDraft.contractors||[]).map(c=>c.name));adminDraft.contractors??=[];for(const c of allOwners())if(!known.has(c.name))adminDraft.contractors.push({name:c.name,visible:false});const body=`<div class="notice">Настройки действуют в открытой вкладке. Применение скачает конфиг; разместите его на SharePoint вручную. Финансовые значения изменяются в исходном Excel.</div><div class="formgrid" style="margin-top:18px"><label>Название приложения<input data-global="title" value="${esc(config.title)}"></label><label>Единицы по умолчанию<select data-global="defaultScale"><option value="1">Единицы</option><option value="1000">Тысячи</option><option value="1000000">Миллионы</option></select></label><label>Округление по умолчанию<select data-global="defaultDecimals"><option value="0">До целого</option><option value="1">1 знак</option><option value="2">2 знака</option></select></label><label class="wide">Прямая ссылка на Excel SharePoint<input data-global="sourceUrl" value="${esc(config.sourceUrl)}" placeholder="https://…/Баланс.xlsx"></label><label class="wide">Адрес файла конфигурации для первого запуска<input data-global="configUrl" value="${esc(config.configUrl)}" placeholder="https://…/balance-config.json"></label><label class="wide">Рабочая папка SharePoint в левом меню<input data-global="workspaceUrl" value="${esc(config.workspaceUrl)}" placeholder="https://…/Документы"></label><label>Доступ к источнику<select data-global="credentials"><option value="same-origin">Текущий сайт</option><option value="include">С авторизацией</option><option value="omit">Без авторизации</option></select></label></div>
<section class="adminsection"><div class="adminbody"><h3>Отображение</h3><label class="admin-check"><input type="checkbox" data-global="showKpis" ${config.showKpis?'checked':''}>Ключевые показатели в хедере</label><h3>Видимые подрядчики</h3><div class="admin-owners">${adminDraft.contractors.map((c,i)=>`<label class="admin-check ${known.has(c.name)?'':'new-owner'}"><input type="checkbox" data-owner-index="${i}" ${c.visible?'checked':''}>${esc(c.name)}${known.has(c.name)?'':'<span class="new-tag">Новый · скрыт</span>'}</label>`).join('')}</div></div></section>
${config.reports.map((r,idx)=>adminReport(r,idx)).join('')}<p class="notice warn hidden" id="modalError" role="alert"></p><div class="modalfoot"><button class="btn primary" id="adminApply">Применить и скачать настройки</button><button class="btn" id="adminImport">Открыть конфиг</button><button class="btn" id="adminDownload">Скачать текущий конфиг</button><button class="btn" id="adminHtml">Скачать HTML с настройками</button></div>`;showModal('Администрирование',body);
 document.querySelectorAll('[data-global]').forEach(el=>{if(el.type==='checkbox')el.checked=config[el.dataset.global];else el.value=config[el.dataset.global]??'';});
 $('modalBody').onchange=adminChange;$('adminApply').onclick=applyAdmin;$('adminImport').onclick=()=>$('configFile').click();$('adminDownload').onclick=()=>download('balance-config.json',JSON.stringify(config,null,2));$('adminHtml').onclick=saveHtml;
}
function adminReport(r,idx){let parsed=null;try{if(book)parsed=extractReport(book,r);}catch{}let columns=[];const sheet=book?.sheets.find(s=>s.name===r.sheet);if(sheet)for(let i=colIndex(r.firstColumn);i<=colIndex(r.lastColumn);i++){const letter=columnName(i),o=r.columns[letter]||{},auto=parsed?.columns.some(c=>c.letter===letter);columns.push({letter,owner:o.contractor??clean(getCell(sheet,i,r.contractorRow)),contract:o.contract??clean(getCell(sheet,i,r.contractRow)),project:o.project??clean(getCell(sheet,i,r.projectRow)),currency:o.currency||r.currency,rate:o.rate??getCell(sheet,i,r.rateRow),include:o.include===undefined?'auto':String(o.include),auto});}
 const field=(key,label,type='text')=>`<label>${label}<input data-report="${idx}" data-field="${key}" type="${type}" value="${esc(r[key])}"></label>`;
 return `<details class="adminsection"><summary>${esc(r.label)} · ${r.currencyMode==='rub'?'RUB':'валюта договора'} / ${r.vat==='gross'?'с НДС':'без НДС'}</summary><div class="adminbody"><div class="formgrid">${field('label','Название отчёта')}${field('sheet','Точное название листа Excel')}${field('currency','Валюта исходника (RUB, USD…)')}${field('firstColumn','Первая колонка (C, E…)')}${field('lastColumn','Последняя колонка (AQ, AL…)')}${field('labelColumn','Колонка названий показателей')}${field('firstRow','Первая строка показателей','number')}${field('lastRow','Последняя строка показателей','number')}${field('contractorRow','Строка названий подрядчиков','number')}${field('contractRow','Строка номеров договоров','number')}${field('projectRow','Строка проектов / видов работ','number')}${field('rateRow','Строка курсов','number')}${field('sourceScale','Множитель сумм источника (млн = 1000000)','number')}${field('dateCell','Ячейка даты актуальности')}<label>Четыре KPI: номера строк через запятую<input data-report="${idx}" data-field="kpis" value="${r.kpis.join(',')}"></label></div><p class="sub" style="margin-top:14px">Если изменили диапазон или лист, примените настройки и снова откройте этот блок для обновления карт колонок и строк.</p>
${columns.length?`<h3 style="margin-top:20px;font-size:14px">Подрядчики и договоры · карта колонок</h3><div class="tablewrap"><table><thead><tr><th>Колонка</th><th>Включение</th><th>Подрядчик</th><th>Договор</th><th>Проект</th><th>Валюта</th><th>Курс к RUB</th></tr></thead><tbody>${columns.map(c=>`<tr><td>${c.letter}<small style="display:block;color:var(--muted)">${c.auto?'договор':'исключена'}</small></td><td><select data-report="${idx}" data-column="${c.letter}" data-colfield="include"><option value="auto" ${c.include==='auto'?'selected':''}>Автоматически</option><option value="true" ${c.include==='true'?'selected':''}>Включить</option><option value="false" ${c.include==='false'?'selected':''}>Исключить</option></select></td>${['owner','contract','project','currency','rate'].map(k=>`<td><input aria-label="${esc(k+' '+c.letter)}" data-report="${idx}" data-column="${c.letter}" data-colfield="${k==='owner'?'contractor':k}" value="${esc(c[k])}" ${k==='rate'?'type="number" min="0.000001" step="any"':''}></td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="sub" style="margin-top:14px">Откройте исходный Excel, чтобы настроить отдельные колонки.</p>'}
${parsed?`<h3 style="margin-top:20px;font-size:14px">Показатели · карта строк</h3><div class="tablewrap"><table><thead><tr><th>Строка</th><th>Показатель</th><th>Видимость</th><th>Тип</th><th>Отступ</th><th>Выделение</th></tr></thead><tbody>${Array.from({length:r.lastRow-r.firstRow+1},(_,j)=>r.firstRow+j).map(n=>{const o=r.rows[n]||{},label=o.label??clean(getCell(sheet,r.labelColumn,n));if(!label)return '';return `<tr><td>${n}</td><td><input data-report="${idx}" data-row="${n}" data-rowfield="label" value="${esc(label)}"></td><td><input type="checkbox" aria-label="Показать строку ${n}" data-report="${idx}" data-row="${n}" data-rowfield="visible" ${o.visible===false?'':'checked'}></td><td><select data-report="${idx}" data-row="${n}" data-rowfield="type">${[['money','Сумма'],['percent','Процент'],['section','Заголовок группы']].map(([v,l])=>`<option value="${v}" ${(o.type||(/доля/i.test(label)?'percent':'money'))===v?'selected':''}>${l}</option>`).join('')}</select></td><td><input type="number" min="0" max="6" placeholder="Excel" data-report="${idx}" data-row="${n}" data-rowfield="indent" value="${o.indent??''}"></td><td><select data-report="${idx}" data-row="${n}" data-rowfield="strong"><option value="auto" ${o.strong===undefined?'selected':''}>Как в Excel</option><option value="true" ${o.strong===true?'selected':''}>Выделить</option><option value="false" ${o.strong===false?'selected':''}>Обычная</option></select></td></tr>`;}).join('')}</tbody></table></div>`:''}</div></details>`;
}
function adminChange(e){const el=e.target;if(el.dataset.ownerIndex!==undefined){adminDraft.contractors[Number(el.dataset.ownerIndex)].visible=el.checked;return;}if(el.dataset.global){const k=el.dataset.global;adminDraft[k]=k==='showKpis'?el.checked:['defaultScale','defaultDecimals'].includes(k)?Number(el.value):el.value.trim();return;}if(el.dataset.report===undefined)return;const r=adminDraft.reports[Number(el.dataset.report)];if(el.dataset.field){const k=el.dataset.field;r[k]=k==='kpis'?el.value.split(',').map(s=>Number(s.trim())):['firstRow','lastRow','contractorRow','contractRow','projectRow','rateRow','sourceScale'].includes(k)?Number(el.value):el.value.trim();}else if(el.dataset.column){const col=el.dataset.column,k=el.dataset.colfield;r.columns[col]??={};if(k==='include'){if(el.value==='auto')delete r.columns[col].include;else r.columns[col].include=el.value==='true';}else if(k==='rate'){if(el.value==='')delete r.columns[col].rate;else r.columns[col].rate=Number(el.value);}else r.columns[col][k]=el.value.trim();}else if(el.dataset.row){const row=el.dataset.row,k=el.dataset.rowfield;r.rows[row]??={};if(k==='indent'){if(el.value==='')delete r.rows[row].indent;else r.rows[row].indent=Number(el.value);}else if(k==='strong'){if(el.value==='auto')delete r.rows[row].strong;else r.rows[row].strong=el.value==='true';}else r.rows[row][k]=k==='visible'?el.checked:el.value;}}
function getDraft(){const active=document.activeElement;if(active&&$('modalBody').contains(active))active.dispatchEvent(new Event('change',{bubbles:true}));const candidate=validateConfig(clone(adminDraft));if(book)for(const r of candidate.reports.filter(r=>book.sheets.some(s=>s.name===r.sheet)))extractReport(book,r);return candidate;}
function adminError(e){$('modalError').textContent=e.message;$('modalError').classList.remove('hidden');$('modalError').scrollIntoView({block:'nearest'});}
function applyAdmin(){try{const next=getDraft(),sourceChanged=config.sourceUrl!==next.sourceUrl;config=next;updateConfigUI();if(book){syncOwnerVisibility();resetSelection();}download('balance-config.json',JSON.stringify(config,null,2));closeModal();render();if(sourceChanged&&config.sourceUrl)runLoad(()=>loadUrl(config.sourceUrl));}catch(e){adminError(e);}}
function saveHtml(){try{const next=getDraft();const html=document.documentElement.cloneNode(true);html.querySelector('body').classList.remove('editing');html.querySelector('#editToggle').setAttribute('aria-pressed','false');html.querySelector('#editToggle').classList.remove('active');html.querySelector('#connectionStatus').className='status-chip';html.querySelector('#modalBack').classList.add('hidden');html.querySelector('#modalBody').innerHTML='';html.querySelector('#dashboard').classList.add('hidden');html.querySelector('#welcome').classList.remove('hidden');html.querySelector('#ownerMenu').innerHTML='<div class="sub">Откройте Excel, чтобы выбрать подрядчика.</div>';html.querySelector('#ownerCount').textContent='—';html.querySelector('#kpis').innerHTML='';html.querySelector('#newOwnersNotice').classList.add('hidden');html.querySelector('#loadStatus').textContent='Источник не открыт';html.querySelector('#appTitle').textContent=next.title;const script=html.querySelector('script:not([type])');script.textContent=script.textContent.replace(/const BOOT_CONFIG = .*?;\n/,()=>`const BOOT_CONFIG = ${JSON.stringify(next).replace(/</g,'\\u003c')};\n`);download('balance-dashboard.html','<!doctype html>\n'+html.outerHTML,'text/html;charset=utf-8');}catch(e){adminError(e);}}
$('excelFile').onchange=()=>{const file=$('excelFile').files[0];if(file)runLoad(async()=>{await loadBook(await file.arrayBuffer(),file.name,'file');closeModal();});$('excelFile').value='';};
$('configFile').onchange=async()=>{const file=$('configFile').files[0];if(!file)return;try{const next=validateConfig(JSON.parse(await file.text()));config=next;updateConfigUI();if(book){syncOwnerVisibility();resetSelection();}closeModal();render();if(config.sourceUrl)await runLoad(()=>loadUrl(config.sourceUrl));}catch(e){if($('modalError'))adminError(e);else alert(e.message);}$('configFile').value='';};
for(const id of ['guideSide','guideWelcome'])$(id).onclick=guide;
$('sourceSide').onclick=sourceDialog;$('sourceWelcome').onclick=connectSource;$('editToggle').onclick=()=>setEditing(!editing);$('notesButton').onclick=showNotes;
$('adminSide').onclick=admin;$('loadFileWelcome').onclick=()=>$('excelFile').click();$('loadEmbedded').onclick=()=>runLoad(loadEmbeddedSource);
$('allContractors').onclick=()=>chooseOwner(null);$('ownerSearch').oninput=()=>{if(book)renderMenu();};$('ownerMenu').onclick=e=>{const el=e.target.closest('[data-owner]');if(el)chooseOwner(el.dataset.owner);};
$('contractChips').onchange=e=>{if(e.target.dataset.contract){e.target.checked?selected.add(e.target.dataset.contract):selected.delete(e.target.dataset.contract);render();}};
$('selectAll').onclick=()=>{resetSelection();render();};$('selectNone').onclick=()=>{selected.clear();render();};
$('showContractorTotal').onchange=render;
for(const id of ['scale','decimals'])$(id).onchange=render;$('detailLevel').onchange=()=>{expandedRows.clear();render();};$('metricSearch').oninput=render;
$('sourceReport').onchange=()=>openReport($('sourceReport').value);
$('newOwnersNotice').onclick=()=>{setEditing(true);admin();};
$('reportArea').onclick=e=>{const group=e.target.closest('[data-toggle-row]');if(group){toggleRow(group.dataset.toggleRow);return;}const ownerButton=e.target.closest('[data-open-owner]');if(ownerButton){chooseOwner(ownerButton.dataset.openOwner);tab='detail';render();}const action=e.target.closest('[data-source-action]')?.dataset.sourceAction;if(action==='file')$('excelFile').click();if(action==='connect')connectSource();if(action==='admin')admin();};
$('refreshSource').onclick=()=>{if(!editing)return;if(sourceInfo?.kind==='url')runLoad(()=>loadUrl(sourceInfo.url));else if(sourceInfo?.kind==='embedded')runLoad(loadEmbeddedSource);else $('excelFile').click();};
$('exportCsv').onclick=exportCsv;$('exportXlsx').onclick=exportXlsx;$('printReport').onclick=()=>window.print();$('modalClose').onclick=closeModal;
$('modalBack').onclick=e=>{if(e.target===$('modalBack'))closeModal();};document.addEventListener('keydown',e=>{if($('modalBack').classList.contains('hidden'))return;if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const nodes=[...$('modalBack').querySelectorAll('button,input,select,a[href],summary')].filter(x=>!x.disabled&&x.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
async function boot(){try{config=validateConfig(clone(BOOT_CONFIG||DEFAULT_CONFIG));activeReport=preferredReport(config.reports).id;$('detailLevel').value='2';const external=new URL(location.href).searchParams.get('config')||config.configUrl;if(external){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const res=await fetch(safeURL(external),{cache:'no-store',credentials:config.credentials,signal:controller.signal});if(!res.ok)throw Error('Конфигурация: HTTP '+res.status);config=validateConfig(await res.json());activeReport=preferredReport(config.reports).id;}finally{clearTimeout(timer);}}updateConfigUI();if(config.sourceUrl)await runLoad(()=>loadUrl(config.sourceUrl));else if($('embedded-source').textContent.trim())await runLoad(loadEmbeddedSource);}catch(e){setLoadStatus('Конфигурация не загружена','error');$('welcome').querySelector('.sub').textContent='Не удалось открыть конфигурацию: '+e.message+'. Её можно импортировать в администрировании.';}}
boot();
