function admin(){if(!editing)return;adminDraft=clone(config);if(adminDraft.contractors===null)adminDraft.contractors=allOwners().map(c=>({name:c.name,visible:true}));const known=new Set((adminDraft.contractors||[]).map(c=>c.name));adminDraft.contractors??=[];for(const c of allOwners())if(!known.has(c.name))adminDraft.contractors.push({name:c.name,visible:false});const body=`<div class="notice">После применения скачивается balance-config.json. Замените им конфиг рядом с HTML на SharePoint — при следующем открытии настройки загрузятся автоматически. Для работы одним файлом скачайте HTML с настройками и замените им страницу приложения. Финансовые значения изменяются в исходном Excel.</div><div class="formgrid" style="margin-top:18px"><label>Название приложения<input data-global="title" value="${esc(config.title)}"></label><label>Единицы по умолчанию<select data-global="defaultScale"><option value="1">Единицы</option><option value="1000">Тысячи</option><option value="1000000">Миллионы</option></select></label><label>Округление по умолчанию<select data-global="defaultDecimals"><option value="0">До целого</option><option value="1">1 знак</option><option value="2">2 знака</option></select></label><label class="wide">Прямая ссылка на Excel SharePoint<input data-global="sourceUrl" value="${esc(config.sourceUrl)}" placeholder="https://…/Баланс.xlsx"></label><label class="wide">Адрес файла конфигурации (необязательно, если он рядом с HTML)<input data-global="configUrl" value="${esc(config.configUrl)}" placeholder="Автоматически: balance-config.json рядом с HTML"></label><label class="wide">Рабочая папка SharePoint в левом меню<input data-global="workspaceUrl" value="${esc(config.workspaceUrl)}" placeholder="https://…/Документы"></label><label>Доступ к источнику<select data-global="credentials"><option value="same-origin">Текущий сайт</option><option value="include">С авторизацией</option><option value="omit">Без авторизации</option></select></label></div>
<section class="adminsection"><div class="adminbody"><h3>Отображение</h3><label class="admin-check"><input type="checkbox" data-global="showKpis" ${config.showKpis?'checked':''}>Ключевые показатели в хедере выбранного подрядчика</label><label class="admin-check"><input type="checkbox" data-global="hideUnavailableContractors" ${config.hideUnavailableContractors?'checked':''}>Скрывать подрядчиков без данных в выбранном исходном листе</label><p class="sub">Подрядчики без значений скрываются из меню и общего баланса. Нулевые значения считаются данными.</p><label class="advance-position">Блок зачёта авансов<select data-global="advanceBlockPosition"><option value="balance">Под балансом</option><option value="bridge">Под мостом</option></select></label><h3 style="margin-top:16px">Видимые подрядчики</h3><div class="admin-owners">${adminDraft.contractors.map((c,i)=>`<label class="admin-check ${known.has(c.name)?'':'new-owner'}"><input type="checkbox" data-owner-index="${i}" ${c.visible?'checked':''}>${esc(c.name)}${known.has(c.name)?'':'<span class="new-tag">Новый · скрыт</span>'}</label>`).join('')}</div></div></section>
<section class="adminsection"><div class="adminbody"><h3>ИИ-поиск GLM</h3><div class="formgrid"><label class="wide">Адрес API<input data-ai="endpoint" type="url" value="${esc(config.aiSearch.endpoint)}"></label><label>Модель<input data-ai="model" value="${esc(config.aiSearch.model)}"></label><label>API-ключ · Bearer<input data-ai="apiKey" type="password" autocomplete="off" value="${esc(config.aiSearch.apiKey)}"></label><label>Оба поиска при запуске<select data-ai="mode"><option value="ai" ${config.aiSearch.mode==='ai'?'selected':''}>ИИ</option><option value="text" ${config.aiSearch.mode==='text'?'selected':''}>Текстовый</option></select></label></div><p class="sub">Настройки подключения сохраняются в balance-config.json. Нажмите значок ИИ для выбора режима, Enter или ↵ для поиска. Результаты отбираются из текущего Excel.</p></div></section>
${config.reports.map((r,idx)=>adminReport(r,idx)).join('')}<p class="notice warn hidden" id="modalError" role="alert"></p><div class="modalfoot"><button class="btn primary" id="adminApply">Применить и скачать настройки</button><button class="btn" id="adminImport">Открыть конфиг</button><button class="btn" id="adminDownload">Скачать текущий конфиг</button><button class="btn" id="adminHtml">Скачать HTML с настройками</button></div>`;showModal('Администрирование',body);
 document.querySelectorAll('[data-global]').forEach(el=>{if(el.type==='checkbox')el.checked=config[el.dataset.global];else el.value=config[el.dataset.global]??'';});
 $('modalBody').querySelectorAll('[data-global],[data-report],[data-owner-index],[data-ai]').forEach(el=>el.dataset.initialValue=String(el.type==='checkbox'?el.checked:el.value));
 $('modalBody').onchange=adminChange;$('modalBody').oninput=adminChange;$('adminApply').onclick=applyAdmin;$('adminImport').onclick=()=>$('configFile').click();$('adminDownload').onclick=applyAdmin;$('adminHtml').onclick=saveHtml;
}
function adminReport(r,idx){let parsed=null;try{if(book)parsed=extractReport(book,r);}catch{}let columns=[];const sheet=book?.sheets.find(s=>s.name===r.sheet);if(sheet)for(let i=colIndex(r.firstColumn);i<=colIndex(r.lastColumn);i++){const letter=columnName(i),o=r.columns[letter]||{},auto=parsed?.columns.some(c=>c.letter===letter);columns.push({letter,owner:o.contractor??clean(getCell(sheet,i,r.contractorRow)),contract:o.contract??clean(getCell(sheet,i,r.contractRow)),project:o.project??clean(getCell(sheet,i,r.projectRow)),currency:o.currency||r.currency,rate:o.rate??getCell(sheet,i,r.rateRow),include:o.include===undefined?'auto':String(o.include),auto});}
 const field=(key,label,type='text')=>`<label>${label}<input data-report="${idx}" data-field="${key}" type="${type}" value="${esc(r[key])}"></label>`;
 return `<details class="adminsection"><summary>${esc(r.label)} · ${r.currencyMode==='rub'?'RUB':'валюта договора'} / ${r.vat==='gross'?'с НДС':'без НДС'}</summary><div class="adminbody"><div class="formgrid">${field('label','Название отчёта')}${field('sheet','Точное название листа Excel')}${field('currency','Валюта исходника (RUB, USD…)')}${field('firstColumn','Первая колонка (C, E…)')}${field('lastColumn','Последняя колонка (AQ, AL…)')}${field('labelColumn','Колонка названий показателей')}${field('firstRow','Первая строка показателей','number')}${field('lastRow','Последняя строка показателей','number')}${field('contractorRow','Строка названий подрядчиков','number')}${field('contractRow','Строка номеров договоров','number')}${field('projectRow','Строка проектов / видов работ','number')}${field('rateRow','Строка курсов','number')}${field('sourceScale','Множитель сумм источника (млн = 1000000)','number')}${field('dateCell','Ячейка даты актуальности')}<label>Четыре KPI: номера строк через запятую<input data-report="${idx}" data-field="kpis" value="${r.kpis.join(',')}"></label></div><p class="sub" style="margin-top:14px">Если изменили диапазон или лист, примените настройки и снова откройте этот блок для обновления карт колонок и строк.</p>
<h3 style="margin-top:20px;font-size:14px">Мост оплат · строки исходного листа</h3><div class="formgrid">${BRIDGE_FIELDS.map(([key,label])=>`<label>${esc(label)}<input data-report="${idx}" data-bridge="${key}" value="${esc((r.bridge?.[key]||[]).join(','))}" placeholder="Номера строк через запятую"></label>`).join('')}</div>
<h3 style="margin-top:20px;font-size:14px">Зачёт авансов · строки исходного листа</h3><div class="formgrid">${ADVANCE_FIELDS.map(([key,label])=>`<label>${esc(label)}<input data-report="${idx}" data-advance="${key}" value="${esc((r.advanceMetrics?.[key]||[]).join(','))}" placeholder="Номера строк через запятую"></label>`).join('')}</div>
${columns.length?`<h3 style="margin-top:20px;font-size:14px">Подрядчики и договоры · карта колонок</h3><div class="tablewrap"><table><thead><tr><th>Колонка</th><th>Включение</th><th>Подрядчик</th><th>Договор</th><th>Проект</th><th>Валюта</th><th>Курс к RUB</th></tr></thead><tbody>${columns.map(c=>`<tr><td>${c.letter}<small style="display:block;color:var(--muted)">${c.auto?'договор':'исключена'}</small></td><td><select data-report="${idx}" data-column="${c.letter}" data-colfield="include"><option value="auto" ${c.include==='auto'?'selected':''}>Автоматически</option><option value="true" ${c.include==='true'?'selected':''}>Включить</option><option value="false" ${c.include==='false'?'selected':''}>Исключить</option></select></td>${['owner','contract','project','currency','rate'].map(k=>`<td><input aria-label="${esc(k+' '+c.letter)}" data-report="${idx}" data-column="${c.letter}" data-colfield="${k==='owner'?'contractor':k}" value="${esc(c[k])}" ${k==='rate'?'type="number" min="0.000001" step="any"':''}></td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="sub" style="margin-top:14px">Откройте исходный Excel, чтобы настроить отдельные колонки.</p>'}
${parsed?`<h3 style="margin-top:20px;font-size:14px">Показатели · карта строк</h3><div class="tablewrap"><table><thead><tr><th>Строка</th><th>Показатель</th><th>Видимость</th><th>Тип</th><th>Отступ</th><th>Выделение</th></tr></thead><tbody>${Array.from({length:r.lastRow-r.firstRow+1},(_,j)=>r.firstRow+j).map(n=>{const o=r.rows[n]||{},label=o.label??clean(getCell(sheet,r.labelColumn,n));if(!label)return '';return `<tr><td>${n}</td><td><input data-report="${idx}" data-row="${n}" data-rowfield="label" value="${esc(label)}"></td><td><input type="checkbox" aria-label="Показать строку ${n}" data-report="${idx}" data-row="${n}" data-rowfield="visible" ${o.visible===false?'':'checked'}></td><td><select data-report="${idx}" data-row="${n}" data-rowfield="type">${[['money','Сумма'],['percent','Процент'],['section','Заголовок группы']].map(([v,l])=>`<option value="${v}" ${(o.type||(/доля/i.test(label)?'percent':'money'))===v?'selected':''}>${l}</option>`).join('')}</select></td><td><input type="number" min="0" max="6" placeholder="Excel" data-report="${idx}" data-row="${n}" data-rowfield="indent" value="${o.indent??''}"></td><td><select data-report="${idx}" data-row="${n}" data-rowfield="strong"><option value="auto" ${o.strong===undefined?'selected':''}>Как в Excel</option><option value="true" ${o.strong===true?'selected':''}>Выделить</option><option value="false" ${o.strong===false?'selected':''}>Обычная</option></select></td></tr>`;}).join('')}</tbody></table></div>`:''}</div></details>`;
}
function adminChange(e){const el=e.target;if(el.dataset.ai){adminDraft.aiSearch[el.dataset.ai]=el.value.trim();return;}if(el.dataset.ownerIndex!==undefined){adminDraft.contractors[Number(el.dataset.ownerIndex)].visible=el.checked;return;}if(el.dataset.global){const k=el.dataset.global;adminDraft[k]=['showKpis','hideUnavailableContractors'].includes(k)?el.checked:['defaultScale','defaultDecimals'].includes(k)?Number(el.value):el.value.trim();return;}if(el.dataset.report===undefined)return;const r=adminDraft.reports[Number(el.dataset.report)];if(el.dataset.field){const k=el.dataset.field;r[k]=k==='kpis'?el.value.split(',').map(s=>Number(s.trim())):['firstRow','lastRow','contractorRow','contractRow','projectRow','rateRow','sourceScale'].includes(k)?Number(el.value):el.value.trim();}else if(el.dataset.advance){r.advanceMetrics??={};r.advanceMetrics[el.dataset.advance]=el.value.trim()?el.value.split(',').map(s=>Number(s.trim())):[];}else if(el.dataset.bridge){r.bridge??={};r.bridge[el.dataset.bridge]=el.value.trim()?el.value.split(',').map(s=>Number(s.trim())):[];}else if(el.dataset.column){const col=el.dataset.column,k=el.dataset.colfield;r.columns[col]??={};if(k==='include'){if(el.value==='auto')delete r.columns[col].include;else r.columns[col].include=el.value==='true';}else if(k==='rate'){if(el.value==='')delete r.columns[col].rate;else r.columns[col].rate=Number(el.value);}else r.columns[col][k]=el.value.trim();}else if(el.dataset.row){const row=el.dataset.row,k=el.dataset.rowfield;r.rows[row]??={};if(k==='indent'){if(el.value==='')delete r.rows[row].indent;else r.rows[row].indent=Number(el.value);}else if(k==='strong'){if(el.value==='auto')delete r.rows[row].strong;else r.rows[row].strong=el.value==='true';}else r.rows[row][k]=k==='visible'?el.checked:el.value;}}
function getDraft(){$('modalBody').querySelectorAll('[data-global],[data-report],[data-owner-index],[data-ai]').forEach(el=>{if(String(el.type==='checkbox'?el.checked:el.value)!==el.dataset.initialValue)adminChange({target:el});});const candidate=validateConfig(clone(adminDraft));if(book)for(const r of candidate.reports.filter(r=>book.sheets.some(s=>s.name===r.sheet)))extractReport(book,r);return candidate;}
function adminError(e){$('modalError').textContent=e.message;$('modalError').classList.remove('hidden');$('modalError').scrollIntoView({block:'nearest'});}
function applyAdmin(){try{const next=getDraft(),sourceChanged=config.sourceUrl!==next.sourceUrl;config=next;updateConfigUI();if(book){syncOwnerVisibility();resetSelection();}download('balance-config.json',JSON.stringify(config,null,2));closeModal();render();if(config.sourceUrl&&(sourceChanged||!book||sourceInfo?.url!==sourceFileURL(config.sourceUrl).href))runLoad(()=>loadUrl(config.sourceUrl));}catch(e){adminError(e);}}
function configuredHtml(next){const html=document.documentElement.cloneNode(true);html.querySelector('body').classList.remove('editing','snapshot-open');html.querySelector('#printSnapshot')?.remove();html.querySelector('#editToggle').setAttribute('aria-pressed','false');html.querySelector('#editToggle').classList.remove('active');html.querySelector('#connectionStatus').className='status-chip';html.querySelector('#modalBack').classList.add('hidden');html.querySelector('#modalBody').innerHTML='';html.querySelector('#aiSearchStatus').textContent='';html.querySelector('#metricAiStatus').textContent='';html.querySelector('#dashboard').classList.add('hidden');html.querySelector('#welcome').classList.remove('hidden');html.querySelector('#ownerMenu').innerHTML='<div class="sub">Откройте Excel, чтобы выбрать подрядчика.</div>';html.querySelector('#ownerCount').textContent='—';html.querySelector('#kpis').innerHTML='';html.querySelector('#advanceBlock').innerHTML='';html.querySelector('#advanceBlock').classList.add('hidden');html.querySelector('#bridgeColumn').classList.add('hidden');html.querySelector('#paymentBridge').innerHTML='';html.querySelector('#paymentBridge').classList.add('hidden');html.querySelector('#newOwnersNotice').classList.add('hidden');html.querySelector('#loadStatus').textContent='Источник не открыт';html.querySelector('#appTitle').textContent=next.title;const script=html.querySelector('script:not([type])');script.textContent=withBootConfig(script.textContent,next);return '<!doctype html>\n'+html.outerHTML;}
function withBootConfig(script,next){return script.replace(/const BOOT_CONFIG = .*?;\n/,()=>`const BOOT_CONFIG = ${JSON.stringify(next).replace(/</g,'\\u003c')};\n`);}
function saveHtml(){try{const next=getDraft(),content=configuredHtml(next);config=next;updateConfigUI();if(book){syncOwnerVisibility();resetSelection();}download('index.html',content,'text/html;charset=utf-8');closeModal();render();if(config.sourceUrl)runLoad(()=>loadUrl(config.sourceUrl));}catch(e){adminError(e);}}
function finishSettings(){if(adminDraft){try{if(JSON.stringify(getDraft())!==JSON.stringify(config)){applyAdmin();return adminDraft===null;}}catch(e){adminError(e);return false;}}closeModal();return true;}
$('excelFile').onchange=()=>{const file=$('excelFile').files[0];if(file)runLoad(async()=>{await loadBook(await file.arrayBuffer(),file.name,'file','',file.lastModified);closeModal();});$('excelFile').value='';};
$('configFile').onchange=async()=>{const file=$('configFile').files[0];if(!file)return;try{const next=validateConfig(JSON.parse(await file.text()));config=next;updateConfigUI();if(book){syncOwnerVisibility();resetSelection();}closeModal();render();if(config.sourceUrl)await runLoad(()=>loadUrl(config.sourceUrl));}catch(e){if($('modalError'))adminError(e);else alert(e.message);}$('configFile').value='';};
for(const id of ['guideSide','guideWelcome'])$(id).onclick=guide;
$('sourceSide').onclick=sourceDialog;$('sourceWelcome').onclick=connectSource;$('editToggle').onclick=()=>setEditing(!editing);$('notesButton').onclick=showNotes;
$('adminSide').onclick=admin;$('loadFileWelcome').onclick=()=>$('excelFile').click();$('loadEmbedded').onclick=()=>runLoad(loadEmbeddedSource);
$('allContractors').onclick=()=>chooseOwner(null);$('ownerSearch').oninput=()=>{cancelAiSearch();aiPlan=null;aiMessage='';aiError=false;if(book)renderMenu();};$('ownerSearch').onkeydown=e=>{if(e.key==='Enter'&&aiMode){e.preventDefault();runAiSearch();}};$('ownerAiMode').onclick=()=>{cancelAiSearch();aiMode=!aiMode;aiPlan=null;aiMessage='';aiError=false;if(book)renderMenu();else renderAiSearch();};$('ownerAiRun').onclick=runAiSearch;$('ownerMenu').onclick=e=>{const el=e.target.closest('[data-owner]');if(el)chooseOwner(el.dataset.owner);};
$('contractChips').onchange=e=>{if(e.target.dataset.contract){e.target.checked?selected.add(e.target.dataset.contract):selected.delete(e.target.dataset.contract);render();}};
$('selectAll').onclick=()=>{resetSelection();render();};$('selectNone').onclick=()=>{selected.clear();render();};
$('showContractorTotal').onchange=render;
for(const id of ['scale','decimals'])$(id).onchange=render;$('detailLevel').onchange=()=>{expandedRows.clear();render();};$('metricSearch').oninput=()=>{cancelMetricAiSearch();metricAiRows=null;metricAiMessage='';metricAiError=false;render();};$('metricSearch').onkeydown=e=>{if(e.key==='Enter'&&metricAiMode){e.preventDefault();runMetricAiSearch();}};$('metricAiMode').onclick=()=>{cancelMetricAiSearch();metricAiMode=!metricAiMode;metricAiRows=null;metricAiMessage='';metricAiError=false;render();};$('metricAiRun').onclick=runMetricAiSearch;
$('sourceReport').onchange=()=>openReport($('sourceReport').value);
$('newOwnersNotice').onclick=()=>{setEditing(true);admin();};
$('reportArea').onclick=e=>{const group=e.target.closest('[data-toggle-row]');if(group){toggleRow(group.dataset.toggleRow);return;}const ownerButton=e.target.closest('[data-open-owner]');if(ownerButton){chooseOwner(ownerButton.dataset.openOwner);tab='detail';render();}const action=e.target.closest('[data-source-action]')?.dataset.sourceAction;if(action==='file')$('excelFile').click();if(action==='connect')connectSource();if(action==='admin')admin();};
$('refreshSource').onclick=()=>{if(!editing)return;if(sourceInfo?.kind==='url')runLoad(()=>loadUrl(sourceInfo.url));else if(sourceInfo?.kind==='embedded')runLoad(loadEmbeddedSource);else $('excelFile').click();};
$('exportXlsx').onclick=exportXlsx;$('printReport').onclick=openPrintPreview;$('modalClose').onclick=finishSettings;
$('modalBack').onclick=e=>{if(e.target===$('modalBack')&&!adminDraft)closeModal();};document.addEventListener('keydown',e=>{if($('modalBack').classList.contains('hidden'))return;if(e.key==='Escape'){e.preventDefault();finishSettings();}if(e.key==='Tab'){const nodes=[...$('modalBack').querySelectorAll('button,input,select,a[href],summary')].filter(x=>!x.disabled&&x.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
function configCandidates(initial,href=location.href,embedded=BOOT_CONFIG){
 const page=new URL(href),explicit=page.searchParams.get('config')||initial.configUrl;
 if(explicit)return [{url:safeURL(new URL(explicit,page).href).href,optional:false}];
 if(embedded||!['http:','https:'].includes(page.protocol))return [];
 return ['balance-config.json','config/balance-config.json'].map(path=>({url:new URL(path,page).href,optional:true}));
}
async function readConfigUrl(url,credentials,optional=false){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
 try{
  const res=await fetch(safeURL(url),{cache:'no-store',credentials,signal:controller.signal});
  if(optional&&res.status===404)return null;
  if(!res.ok)throw Error('Конфигурация: HTTP '+res.status+'. Проверьте доступ к файлу balance-config.json.');
  const text=await res.text();
  if(/^\s*</.test(text))throw Error('Вместо JSON-конфига SharePoint вернул страницу просмотра или входа. Укажите прямой адрес файла balance-config.json.');
  let next;try{next=JSON.parse(text);}catch{throw Error('Файл конфигурации не содержит корректный JSON.');}
  const base=res.url||safeURL(url).href;
  for(const k of ['sourceUrl','workspaceUrl'])if(next[k])next[k]=new URL(next[k],base).href;
  next.configUrl=safeURL(url).href;
  return validateConfig(next);
 }catch(e){throw Error(e.name==='AbortError'?'Загрузка конфигурации превысила 20 секунд.':e.message==='Failed to fetch'?'Браузер не смог прочитать конфиг. Проверьте прямую ссылку, вход на SharePoint и доступ с домена приложения.':e.message);}finally{clearTimeout(timer);}
}
async function boot(){
 try{
  config=validateConfig(clone(BOOT_CONFIG||DEFAULT_CONFIG));activeReport=preferredReport(config.reports).id;$('detailLevel').value='2';
  for(const candidate of configCandidates(config)){
   const next=await readConfigUrl(candidate.url,config.credentials,candidate.optional);
   if(next){config=next;break;}
  }
  activeReport=preferredReport(config.reports).id;updateConfigUI();
  if(config.sourceUrl)await runLoad(()=>loadUrl(config.sourceUrl));else if($('embedded-source').textContent.trim())await runLoad(loadEmbeddedSource);
 }catch(e){book=null;sourceInfo=null;updateConfigUI();render();setLoadStatus('Конфигурация не загружена','error');$('welcome').querySelector('.sub').textContent='Не удалось открыть конфигурацию: '+e.message+' Включите режим редактирования и откройте конфиг с устройства или исправьте ссылку в администрировании.';}
}
const bootReady=boot();

$('paymentBridge').addEventListener('pointerover',e=>highlightBridgeSource(e.target));$('paymentBridge').addEventListener('pointerout',e=>{if(!e.relatedTarget?.closest?.('[data-bridge-step]'))clearBridgeHighlight();});$('paymentBridge').addEventListener('focusin',e=>highlightBridgeSource(e.target));$('paymentBridge').addEventListener('focusout',clearBridgeHighlight);
