// OOXML export runs in the single HTML, with no network calls or external libraries.
const XLSX_NS='http://schemas.openxmlformats.org/';
function exportStyles(){
 let text=book.stylesXml||`<styleSheet xmlns="${XLSX_NS}spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 const body=tag=>text.match(new RegExp('<'+tag+'\\b[^>]*>([\\s\\S]*?)</'+tag+'>'))?.[1]||'',items=(tag,child)=>(body(tag).match(new RegExp('<'+child+'\\b[^>]*\\/>|<'+child+'\\b[^>]*>[\\s\\S]*?</'+child+'>','g'))||[]);
 const collections={fonts:items('fonts','font'),fills:items('fills','fill'),borders:items('borders','border'),cellXfs:items('cellXfs','xf'),numFmts:items('numFmts','numFmt')};
 const add=(tag,value)=>{const id=collections[tag].length;collections[tag].push(value);return id;},font=(color,bold=false,size=10)=>add('fonts',`<font>${bold?'<b/>':''}<sz val="${size}"/><color rgb="FF${color}"/><name val="Segoe UI"/></font>`),fill=color=>add('fills',`<fill><patternFill patternType="solid"><fgColor rgb="FF${color}"/><bgColor indexed="64"/></patternFill></fill>`);
 const normalFont=font('20303B'),titleFont=font('008C95',true,16),whiteFont=font('FFFFFF',true),boldFont=font('183D49',true),errorFont=font('B23F43');
 const white=fill('FFFFFF'),navy=fill('183D49'),light=fill('EAF0F2'),teal=fill('DFF1F2'),error=fill('FFE0E0'),border=add('borders','<border><left style="thin"><color rgb="FFDBE2E5"/></left><right style="thin"><color rgb="FFDBE2E5"/></right><top style="thin"><color rgb="FFDBE2E5"/></top><bottom style="thin"><color rgb="FFDBE2E5"/></bottom><diagonal/></border>');
 const dp=Number($('decimals').value),zeros=dp?'.'+'0'.repeat(dp):'',moneyId=Math.max(163,...collections.numFmts.map(x=>Number(x.match(/numFmtId="(\d+)"/)?.[1])||0))+1,percentId=moneyId+1;
 add('numFmts',`<numFmt numFmtId="${moneyId}" formatCode="#,##0${zeros};-#,##0${zeros};&quot;—&quot;"/>`);add('numFmts',`<numFmt numFmtId="${percentId}" formatCode="0${zeros}%;-0${zeros}%;&quot;—&quot;"/>`);
 const xf=(fontId,fillId,numFmtId=0,alignment='horizontal="center" vertical="center" wrapText="1"')=>add('cellXfs',`<xf numFmtId="${numFmtId}" fontId="${fontId}" fillId="${fillId}" borderId="${border}" xfId="0" applyAlignment="1" applyNumberFormat="1"><alignment ${alignment}/></xf>`);
 const ids={title:xf(titleFont,white,0,'horizontal="left" vertical="center" wrapText="1"'),meta:xf(normalFont,white,0,'horizontal="left" vertical="center" wrapText="1"'),head:xf(whiteFont,navy),label:xf(boldFont,light,0,'horizontal="left" vertical="center" wrapText="1"'),money:xf(normalFont,white,moneyId),percent:xf(normalFont,white,percentId),total:xf(boldFont,teal,moneyId),error:xf(errorFont,error,moneyId)};
 const originals=items('cellXfs','xf'),cache=new Map();
 function sourceStyle(base,type,bad=false){
  const key=[base,type,bad].join('|');if(cache.has(key))return cache.get(key);let value=originals[base]||originals[0]||'<xf fontId="0" fillId="0" borderId="0" numFmtId="0"/>';
  const attr=(name,next)=>{value=value.replace(new RegExp(' '+name+'="[^"]*"','g'),'').replace('<xf','<xf '+name+'="'+next+'"');};
  if(type){attr('numFmtId',type==='percent'?percentId:moneyId);attr('applyNumberFormat',1);}if(bad){attr('fillId',error);attr('fontId',errorFont);attr('applyFill',1);attr('applyFont',1);}
  const id=add('cellXfs',value);cache.set(key,id);return id;
 }
 function finish(){for(const [tag,values] of Object.entries(collections)){const replacement=`<${tag} count="${values.length}">${values.join('')}</${tag}>`,re=new RegExp('<'+tag+'\\b[^>]*(?:\\/>|>[\\s\\S]*?</'+tag+'>)');text=re.test(text)?text.replace(re,replacement):text.replace(/(<styleSheet\b[^>]*>)/,'$1'+replacement);}return text;}
 return {ids,sourceStyle,finish};
}
function exportCell(ref,value,style,formula){const numeric=typeof value==='number'&&Number.isFinite(value);return numeric?`<c r="${ref}" s="${style}">${formula?'<f>'+xesc(formula)+'</f>':''}<v>${value}</v></c>`:`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xesc(value??'Нет данных')}</t></is></c>`;}
function exportSheet(data,widths,merges=[],drawing=false){
 const last=Math.max(1,...data.map(x=>x.row)),maxCol=Math.max(1,...data.flatMap(x=>x.cells.map(c=>c.col+1))),rows=data.map(x=>`<row r="${x.row}" ht="${x.height||22}" customHeight="1"${x.level?' outlineLevel="'+Math.min(7,x.level)+'"':''}>${x.cells.map(c=>exportCell(columnName(c.col)+x.row,c.value,c.style,c.formula)).join('')}</row>`).join('');
 return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${XLSX_NS}spreadsheetml/2006/main" xmlns:r="${XLSX_NS}officeDocument/2006/relationships"><dimension ref="A1:${columnName(maxCol-1)}${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane xSplit="1" ySplit="${drawing?2:13}" topLeftCell="B${drawing?3:14}" activePane="bottomRight" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="22"/><cols>${widths.map(w=>`<col min="${w.min}" max="${w.max}" width="${w.width}" customWidth="1"${w.hidden?' hidden="1"':''}/>`).join('')}</cols><sheetData>${rows}</sheetData>${merges.length?'<mergeCells count="'+merges.length+'">'+merges.map(ref=>'<mergeCell ref="'+ref+'"/>').join('')+'</mergeCells>':''}<printOptions horizontalCentered="1"/><pageMargins left="0.25" right="0.25" top="0.35" bottom="0.35" header="0.15" footer="0.15"/><pageSetup orientation="landscape" paperSize="9" fitToWidth="1" fitToHeight="0"/>${drawing?'<drawing r:id="rId1"/>':''}</worksheet>`;
}
function balanceExportSheet(style){
 const r=currentReport(),cols=selectedColumns(r),sourceRows=viewRows(r),rows=exportRows(),groups=tab==='summary'?[...new Set(cols.map(c=>groupCurrency(r,c,targetCurrency())))].map(currency=>({columns:cols.filter(c=>groupCurrency(r,c,targetCurrency())===currency)})).concat(summaryGroups(r,cols)):cols.map(c=>({columns:[c]}));
 const data=rows.map((values,index)=>{const source=index>=13&&index<13+sourceRows.length?sourceRows[index-13]:null;return {row:index+1,height:source?Math.max(18,r.sheet.rowHeights?.[source.row]||18):index===0?32:index===10?Math.max(35,r.sheet.rowHeights?.[r.report.contractorRow]||35):index===12?Math.max(36,r.sheet.rowHeights?.[r.report.projectRow]||36):22,level:source?Math.max(0,(source.level||1)-1):0,cells:values.map((value,col)=>{
  let id=index===0?style.ids.title:index<9?style.ids.meta:index<13?style.ids.head:style.ids.meta;
  if(source){const originCol=col===0?r.report.labelColumn:tab==='detail'?cols[col-1]?.letter:'C',base=r.sheet.cellStyles?.[originCol+source.row]?.styleId||0,type=col>0&&typeof value==='number'?source.type:null,bad=col>0&&groups[col-1]?.columns.some(c=>invalidPositive(source,selectedValue(r,c,source,targetCurrency())));id=style.sourceStyle(base,type,bad);}
  else if(index>=9&&index<=12){const sourceLine={9:r.report.contractRow,10:r.report.contractorRow,12:r.report.projectRow}[index],originCol=col===0?r.report.labelColumn:tab==='detail'?cols[col-1]?.letter:'C',base=sourceLine?r.sheet.cellStyles?.[originCol+sourceLine]?.styleId:undefined;if(base!==undefined)id=style.sourceStyle(base,null);}
  return {col,value,style:id};})};});
 const width=letter=>{const n=colIndex(letter)+1;return r.sheet.columnWidths?.find(w=>w.min<=n&&w.max>=n)?.width;},count=Math.max(2,rows[9].length),widths=[{min:1,max:1,width:Math.max(38,width(r.report.labelColumn)||40)}];
 for(let col=1;col<count;col++)widths.push({min:col+1,max:col+1,width:Math.max(12,tab==='detail'?width(cols[col-1]?.letter||'C')||14:14)});
 return exportSheet(data,widths);
}
function bridgeChartXml(data,refs,title){
 const count=data.steps.length,categories=data.steps.map(s=>s.label),numberCache=values=>`<c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="${count}"/>${values.map((v,i)=>v===null?'':`<c:pt idx="${i}"><c:v>${v}</c:v></c:pt>`).join('')}</c:numCache>`,category=`<c:strRef><c:f>${xesc(refs.categories)}</c:f><c:strCache><c:ptCount val="${count}"/>${categories.map((v,i)=>`<c:pt idx="${i}"><c:v>${xesc(v)}</c:v></c:pt>`).join('')}</c:strCache></c:strRef>`;
 const rich=text=>`<a:bodyPr/><a:lstStyle/><a:p><a:pPr/><a:r><a:rPr lang="ru-RU" sz="1000"><a:solidFill><a:srgbClr val="20303B"/></a:solidFill></a:rPr><a:t>${xesc(text)}</a:t></a:r><a:endParaRPr lang="ru-RU"/></a:p>`;
 const series=refs.values.map((ref,j)=>{const values=data.steps.map(s=>{if(s.value===null)return null;const lo=Math.min(s.from,s.to),hi=Math.max(s.from,s.to);return j===0?Math.max(0,lo):j===1?Math.min(0,hi):j===2?Math.max(0,hi)-Math.max(0,lo):Math.min(0,lo)-Math.min(0,hi);});
  const points=j<2?'<c:spPr><a:noFill/><a:ln><a:noFill/></a:ln></c:spPr>':data.steps.map((s,i)=>`<c:dPt><c:idx val="${i}"/><c:spPr><a:solidFill><a:srgbClr val="${s.remaining?(s.error?'C63E46':'008C95'):s.total?'183D49':'769EA4'}"/></a:solidFill><a:ln><a:noFill/></a:ln></c:spPr></c:dPt>`).join('');
  const labels=j<2?'':`<c:dLbls>${data.steps.map((s,i)=>{if(s.value===null||(j===2?values[i]===0&&s.value!==0:refs.positive[i]!==0||s.value===0))return '';return `<c:dLbl><c:idx val="${i}"/><c:tx><c:rich>${rich(s.value===0?'—':new Intl.NumberFormat('ru-RU',{minimumFractionDigits:Number($('decimals').value),maximumFractionDigits:Number($('decimals').value)}).format(s.value))}</c:rich></c:tx><c:dLblPos val="outEnd"/><c:showLegendKey val="0"/><c:showVal val="0"/><c:showCatName val="0"/><c:showSerName val="0"/></c:dLbl>`;}).join('')}<c:showLegendKey val="0"/><c:showVal val="0"/><c:showCatName val="0"/><c:showSerName val="0"/></c:dLbls>`;
  return `<c:ser><c:idx val="${j}"/><c:order val="${j}"/>${points}${labels}<c:cat>${category}</c:cat><c:val><c:numRef><c:f>${xesc(ref)}</c:f>${numberCache(values)}</c:numRef></c:val></c:ser>`;
 }).join('');
 return `<?xml version="1.0" encoding="UTF-8"?><c:chartSpace xmlns:c="${XLSX_NS}drawingml/2006/chart" xmlns:a="${XLSX_NS}drawingml/2006/main" xmlns:r="${XLSX_NS}officeDocument/2006/relationships"><c:lang val="ru-RU"/><c:chart><c:title><c:tx><c:rich>${rich(title)}</c:rich></c:tx><c:overlay val="0"/></c:title><c:plotArea><c:layout/><c:barChart><c:barDir val="col"/><c:grouping val="stacked"/><c:varyColors val="0"/>${series}<c:gapWidth val="75"/><c:overlap val="100"/><c:axId val="10"/><c:axId val="20"/></c:barChart><c:catAx><c:axId val="10"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="b"/><c:tickLblPos val="nextTo"/><c:crossAx val="20"/><c:crosses val="autoZero"/><c:auto val="1"/><c:lblAlgn val="ctr"/><c:lblOffset val="100"/></c:catAx><c:valAx><c:axId val="20"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="l"/><c:majorGridlines><c:spPr><a:ln w="6350"><a:solidFill><a:srgbClr val="E5ECEE"/></a:solidFill></a:ln></c:spPr></c:majorGridlines><c:numFmt formatCode="#,##0" sourceLinked="0"/><c:tickLblPos val="nextTo"/><c:crossAx val="10"/><c:crosses val="autoZero"/><c:crossBetween val="between"/></c:valAx></c:plotArea><c:plotVisOnly val="0"/><c:dispBlanksAs val="gap"/></c:chart><c:spPr><a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill><a:ln><a:noFill/></a:ln></c:spPr></c:chartSpace>`;
}
function supplementsExportSheet(style){
 const r=currentReport(),cols=selectedColumns(r),names=[...new Set(cols.map(c=>c.contractor))],data=[],merges=[],charts=[],anchors=[],scale=Number($('scale').value),q="'Мост и авансы'!";let next=1,maxVisible=9;
 const row=(number,values,id=style.ids.meta,height=22)=>data.push({row:number,height,cells:values.map((value,col)=>({col,value,style:id}))}),merged=(number,text,id=style.ids.meta,height=25)=>{row(number,[text],id,height);merges.push(`A${number}:I${number}`);};
 for(const name of names)for(const bridge of paymentBridgeData(r,cols.filter(c=>c.contractor===name))){const start=next,chosen=cols.filter(c=>c.contractor===name&&groupCurrency(r,c,targetCurrency())===bridge.currency),advance=advanceMetricsData(r,chosen),valueRow=start+20,forecastRow=start+21;
  merged(start,`${name} · ${bridge.currency}`,style.ids.title,30);merged(start+1,`${unitText(r)} · ${rConfig().label} · сформирован ${currentDateParts().text}`);
  if(bridge.issues.length){merged(start+3,'Нет данных для моста: '+bridge.issues.join(', '),style.ids.meta,40);}else{
   row(valueRow-1,['Показатель мостика',...bridge.steps.map(s=>s.label)],style.ids.head,44);
   const values=bridge.steps.map(s=>s.value===null?'Нет данных':s.value/scale);const item={row:valueRow,height:25,cells:[{col:0,value:'Сумма',style:style.ids.label},...values.map((value,i)=>({col:i+1,value,style:bridge.steps[i].remaining?bridge.steps[i].value<0&&errorMagnitude(bridge.steps[i].value)?style.ids.error:style.ids.total:style.ids.money,formula:i===5?'SUM(B'+valueRow+':F'+valueRow+')':i===6&&typeof value==='number'?'L'+forecastRow+'-B'+valueRow:i===7&&typeof value==='number'?'SUM(G'+valueRow+':H'+valueRow+')':null}))]};data.push(item);
   data.push({row:forecastRow,height:22,helper:true,cells:[{col:11,value:bridge.values.forecastContract===null?'Нет данных':bridge.values.forecastContract/scale,style:style.ids.money}]});
   const scaled={...bridge,steps:bridge.steps.map(s=>({...s,value:s.value===null?null:s.value/scale,from:s.from===null?null:s.from/scale,to:s.to===null?null:s.to/scale}))},refs=[];
   for(let series=0;series<4;series++){const n=start+34+series;refs.push(q+'$L$'+n+':$S$'+n);data.push({row:n,height:22,helper:true,cells:scaled.steps.map((s,i)=>{const before=i===0||i===5||i===7?'0':i===6?'G'+valueRow:'SUM(B'+valueRow+':'+columnName(i)+valueRow+')',after=i===6?'I'+valueRow:i>0&&i<5?'SUM(B'+valueRow+':'+columnName(i+1)+valueRow+')':columnName(i+1)+valueRow,lo=`MIN(${before},${after})`,hi=`MAX(${before},${after})`,formula=series===0?`MAX(0,${lo})`:series===1?`MIN(0,${hi})`:series===2?`MAX(0,${hi})-MAX(0,${lo})`:`MIN(0,${lo})-MIN(0,${hi})`,value=s.value===null?'':series===0?Math.max(0,Math.min(s.from,s.to)):series===1?Math.min(0,Math.max(s.from,s.to)):series===2?Math.max(0,Math.max(s.from,s.to))-Math.max(0,Math.min(s.from,s.to)):Math.min(0,Math.min(s.from,s.to))-Math.min(0,Math.max(s.from,s.to));return {col:11+i,value,style:style.ids.money,formula:s.value===null?null:formula};})});}
   // Colours and label magnitudes use original units; series caches use selected display units.
   const chartData={...scaled,steps:scaled.steps.map((s,i)=>({...s,error:bridge.steps[i].value<0&&errorMagnitude(bridge.steps[i].value)}))};
   const index=charts.length+1;charts.push(bridgeChartXml(chartData,{categories:q+'$B$'+(valueRow-1)+':$I$'+(valueRow-1),values:refs,positive:scaled.steps.map(s=>s.value===null?null:Math.max(0,Math.max(s.from,s.to))-Math.max(0,Math.min(s.from,s.to)))},'От контракта до остатка оплат'));
   anchors.push({index,from:start+1,to:start+18});
  }
  merged(start+22,'Зачёт авансов',style.ids.title,28);row(start+23,['Показатель',...advance.map(d=>d.col.contract)],style.ids.head,32);maxVisible=Math.max(maxVisible,advance.length+1);
  for(let i=0;i<ADVANCE_ROWS.length;i++){const [key,label,type]=ADVANCE_ROWS[i];data.push({row:start+24+i,height:25,cells:[{col:0,value:label,style:style.ids.label},...advance.map((d,j)=>({col:j+1,value:typeof d[key]==='number'?(type==='money'?d[key]/scale:d[key]):d[key]??'Нет данных',style:type==='percent'?style.ids.percent:style.ids.money}))]});}
  merged(start+30,'Расчёт: остаток оплат = контракт − оплаты по актам − авансы + ГУ + КЗ. Динамика = прогноз − подписанная стоимость. Остаток от прогноза = остаток оплат + динамика.',style.ids.meta,38);
  merged(start+31,bridge.forecastRemaining===null?'Отдельный прогноз контракта отсутствует: прогнозный остаток не рассчитан.':'ГУ и КЗ учитываются со знаками исходного баланса.',style.ids.meta,25);
  next=start+41;
 }
 const widths=[{min:1,max:1,width:38},{min:2,max:Math.max(9,maxVisible),width:15}];
 // Place chart helper cells after visible contract columns, never hiding a selected contract.
 const helperOffset=Math.max(11,maxVisible+1);if(helperOffset!==11){for(const item of data)for(const cell of item.cells){if(item.helper&&cell.col>=11)cell.col+=helperOffset-11;}
  for(const item of data)for(const cell of item.cells)if(cell.formula?.startsWith('L'))cell.formula=columnName(helperOffset)+cell.formula.slice(1);
  for(let i=0;i<charts.length;i++)charts[i]=charts[i].replace(/\$L\$/g,'$'+columnName(helperOffset)+'$').replace(/\$S\$/g,'$'+columnName(helperOffset+7)+'$');
 }
 widths.push({min:helperOffset+1,max:helperOffset+8,width:15,hidden:true});data.sort((a,b)=>a.row-b.row);return {xml:exportSheet(data,widths,merges,charts.length>0),charts,anchors};
}
function formattedXlsxFile(){
 const style=exportStyles(),balance=balanceExportSheet(style),extra=supplementsExportSheet(style),files={};
 const rel=(id,type,target)=>`<Relationship Id="${id}" Type="${XLSX_NS}officeDocument/2006/relationships/${type}" Target="${target}"/>`,rels=body=>`<?xml version="1.0"?><Relationships xmlns="${XLSX_NS}package/2006/relationships">${body}</Relationships>`;
 const override=(path,type)=>`<Override PartName="/${path}" ContentType="application/vnd.openxmlformats-officedocument.${type}+xml"/>`;
 files['[Content_Types].xml']=`<?xml version="1.0"?><Types xmlns="${XLSX_NS}package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${override('xl/workbook.xml','spreadsheetml.sheet.main')}${override('xl/styles.xml','spreadsheetml.styles')}${[1,2].map(i=>override('xl/worksheets/sheet'+i+'.xml','spreadsheetml.worksheet')).join('')}${extra.charts.length?override('xl/drawings/drawing1.xml','drawing')+extra.charts.map((_,i)=>override('xl/charts/chart'+(i+1)+'.xml','drawingml.chart')).join(''):''}</Types>`;
 files['_rels/.rels']=rels(rel('rId1','officeDocument','xl/workbook.xml'));files['xl/_rels/workbook.xml.rels']=rels(rel('rId1','worksheet','worksheets/sheet1.xml')+rel('rId2','worksheet','worksheets/sheet2.xml')+rel('rId3','styles','styles.xml'));
 files['xl/workbook.xml']=`<?xml version="1.0"?><workbook xmlns="${XLSX_NS}spreadsheetml/2006/main" xmlns:r="${XLSX_NS}officeDocument/2006/relationships"><sheets><sheet name="Баланс" sheetId="1" r:id="rId1"/><sheet name="Мост и авансы" sheetId="2" r:id="rId2"/></sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`;
 if(book.themeXml){files['xl/theme/theme1.xml']=book.themeXml;files['xl/_rels/workbook.xml.rels']=files['xl/_rels/workbook.xml.rels'].replace('</Relationships>',rel('rId4','theme','theme/theme1.xml')+'</Relationships>');files['[Content_Types].xml']=files['[Content_Types].xml'].replace('</Types>',override('xl/theme/theme1.xml','theme')+'</Types>');}files['xl/styles.xml']=style.finish();files['xl/worksheets/sheet1.xml']=balance;files['xl/worksheets/sheet2.xml']=extra.xml;
 if(extra.charts.length){files['xl/worksheets/_rels/sheet2.xml.rels']=rels(rel('rId1','drawing','../drawings/drawing1.xml'));files['xl/drawings/_rels/drawing1.xml.rels']=rels(extra.charts.map((_,i)=>rel('rId'+(i+1),'chart','../charts/chart'+(i+1)+'.xml')).join(''));
  files['xl/drawings/drawing1.xml']=`<?xml version="1.0"?><xdr:wsDr xmlns:xdr="${XLSX_NS}drawingml/2006/spreadsheetDrawing" xmlns:a="${XLSX_NS}drawingml/2006/main">${extra.anchors.map(a=>`<xdr:twoCellAnchor><xdr:from><xdr:col>0</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${a.from}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:to><xdr:col>9</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${a.to}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="${a.index}" name="Мост оплат ${a.index}"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm><a:graphic><a:graphicData uri="${XLSX_NS}drawingml/2006/chart"><c:chart xmlns:c="${XLSX_NS}drawingml/2006/chart" xmlns:r="${XLSX_NS}officeDocument/2006/relationships" r:id="rId${a.index}"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor>`).join('')}</xdr:wsDr>`;
  extra.charts.forEach((chart,i)=>files['xl/charts/chart'+(i+1)+'.xml']=chart);
 }return zipStored(files);
}
